### ISSUE TITLE
Visuals TODO list

### ISSUE THREAD

**Issue by nohwnd** [pester/docs#71] opened 2020-11-09 13:48 UTC
TODO list for when we seek help from someone who can style Docusaurus: 

---

Caution block that is emited when 

```
:::caution
blah blah
:::
```

is used in the `.mdx` has poor contrast. 

^^^
Nothing wrong with code, but these blocks should probably have more contrast. Can be hard to read in light mode.

_Originally posted by @fflaten in https://github.com/pester/docs/pull/70#r519481674_

--- 

Switching to dark mode not all items are switched, (this started happening after the version dropdown).

---

Pester logo turns black on hover.

**Comment by fflaten** [comment] 2022-06-10 11:56
> ^^^ Nothing wrong with code, but these blocks should probably have more contrast. Can be hard to read in light mode.
> 
> _Originally posted by @fflaten in [#70 (comment)](https://github.com/pester/docs/pull/70#r519481674)_

No complaints from me anymore. Either fixed in newer docusaurus build or when I replaced a 10 years old monitor 😅 

> Switching to dark mode not all items are switched, (this started happening after the version dropdown).

Do you remember what? No longer an issue? Codeblocks will be getting dark mode in #195 

> Pester logo turns black on hover.

Can't reproduce this naymore. Turns blue in light and dark
![image](https://user-images.githubusercontent.com/3436158/173058609-58ba1a15-5a3f-42b4-b9b5-d7810a9fe1a2.png)

Close?

**Comment by bravo-kernel** [comment] 2022-06-10 12:10
I think @nohwnd means these caution blocks which are using the [default admonition colors](https://docusaurus.io/docs/markdown-features/admonitions) (and look good to me).

Considering this ticket is almost two years old and things have changed a lot since then I think we can safely close this one, it can always be re-opened.



![image](https://user-images.githubusercontent.com/230500/173060234-4db8fbe9-5695-4e96-bbd9-b9e79f0800d6.png)

**Closed by bravo-kernel** 2022-06-10 12:10 UTC
